## não é mais necessário em versões recentes do docker: version: "3.9"

services:

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: vrumvrum
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/vrumvrum
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - vrumvrum-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vrumvrum
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vrumvrum-net

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - vrumvrum-net

volumes:
  pgdata:
  redisdata:

networks:
  vrumvrum-net:
    driver: bridge