"""cria tabela audit events

Revision ID: 84d21da7b408
Revises: 20b92e947231
Create Date: 2026-05-21 16:17:08.492200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d21da7b408'
down_revision: Union[str, None] = '20b92e947231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ride_ide', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('lamport_clock', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_novo', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_ride_ide'), 'audit_events', ['ride_ide'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_ride_ide'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
