"""cria tabela rides

Revision ID: b7bda1cc9f75
Revises: 
Create Date: 2026-05-12 18:13:39.736073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bda1cc9f75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('REQUEST', 'MATCH', 'CONFIRM', 'IN_TRANSIT', 'COMPLETE', 'CANCELED', name='ridestatus'), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_street', sa.String(length=255), nullable=False),
    sa.Column('origin_number', sa.String(length=20), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('destination_street', sa.String(length=255), nullable=False),
    sa.Column('destination_number', sa.String(length=20), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('destination_state', sa.String(length=2), nullable=False),
    sa.Column('passenger_id', sa.String(length=255), nullable=False),
    sa.Column('driver_id', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('eta', sa.Integer(), nullable=True),
    sa.Column('delegated_to', sa.String(length=255), nullable=True),
    sa.Column('core_ride_uuid', sa.String(length=36), nullable=True),
    sa.Column('delegation_winner', sa.String(length=255), nullable=True),
    sa.Column('lamport_clock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    # ### end Alembic commands ###
