"""corrige coluna ride_id em audit_events

Revision ID: c0bd994171a0
Revises: 84d21da7b408
Create Date: 2026-05-21 17:22:38.829801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bd994171a0'
down_revision: Union[str, None] = '84d21da7b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('ride_id', sa.String(length=36), nullable=False))
    op.drop_index('ix_audit_events_ride_ide', table_name='audit_events')
    op.create_index(op.f('ix_audit_events_ride_id'), 'audit_events', ['ride_id'], unique=False)
    op.drop_column('audit_events', 'ride_ide')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('ride_ide', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_events_ride_id'), table_name='audit_events')
    op.create_index('ix_audit_events_ride_ide', 'audit_events', ['ride_ide'], unique=False)
    op.drop_column('audit_events', 'ride_id')
    # ### end Alembic commands ###
