# Workflow de CI do VrumVrum

name: Continuous Integration

on: 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: docker compose
        run: |
          docker compose up -d db
          sleep 5

      # setup do banco de dados mockado
      - name: setup test dataset
        run: |
          docker compose exec -T db psql -U postgres -c "CREATE DATABASE vrumvrum_test;"

      # Execução dos testes unitários
      - name: execute unitary tests
        env:
          PYTHONPATH: .
        run: |
          pytest -s -v
